arcanis/clipanion

index.d.ts

Before this PR, actions had to return an exit code or an explicit `undefined`:
```ts
clipanion
.command('example')
.action(() => {
console.log('Hello world');
return 0;
});
// or
clipanion
.command('example')
.action(() => {
console.log('Hello world');
return undefined;
});
```
After this PR, they can skip the return statement:
```ts
clipanion
.command('example')
.action(() => {
console.log('Hello world');
});
```
Running such commands still sets `0` as a return code, as expected:
```console
$ node -r ts-node/register run.ts example
Hello world
$ echo $?
0
```

Allow actions to avoid return statement

---

sources/advanced/Command.ts
sources/core.ts
tests/advanced.test.ts

Ref: https://github.com/yarnpkg/berry/pull/371#discussion_r316198410
Nice-to-have?:
- ~[ ] hyphenate names~
- ~[ ] make name configurable `@Command.String({ name: 'workspace-name' })` or `@Command.String('workspace-name')`. Though the second variant requires more work since the library currently assumes that named arguments are optional.~

feat: Derive name of positional arguments from property name

---

sources/core.ts
tests/core.test.ts

It is currently possible to do `yarn add foo --dev=something`, where `--dev` is a boolean option. This causes `--dev` to be `'something'` at runtime.
I made the `isBoundOption` function also check if the `arity` is `1`.
I also added a test for this feature, and a few other tests for some other awesome Clipanion features that didn't seem to have a corresponding test. 🙂
BTW, it would be nice having automated CI running on this repo, to boost my confidence that the tests I added are passing. :P

 fix(core): throw error when writing bound boolean arguments 

---

sources/advanced/Cli.ts
sources/advanced/Command.ts
sources/advanced/index.ts
sources/errors.ts
tests/advanced.test.ts

The binary information (`binaryLabel`, `binaryName`, and `binaryVersion`) isn't exposed on the `MiniCli`.
It would be useful for things like `-v,--version` commands to just do `this.context.stdout.write(this.cli.binaryVersion);`, rather than `this.context.stdout.write(THE_COMPLEX_WAY_THE_VERSION_IS_COMPUTED_THAT_I_ALREADY_USE_IN_THE_CLI_ENTRY_POINT_FILE);`. 
I made the binary information be exposed on the MiniCli.
---
@arcanis BTW, would you be open to shipping the common command entries (`-v,--version` and `-h,--help`) directly in Clipanion (they would have to be manually registered by the user)?:
```ts
import {VersionEntry, HelpEntry} from 'clipanion';
// ...
cli.register(VersionEntry);
cli.register(HelpEntry);
```
It's …

feat: expose binary information on the MiniCli

---

sources/advanced/Command.ts
sources/advanced/index.ts

The `schema` static property isn't currently typed, meaning that `static schema = 'foo';` is valid.
I made the `schema` static property typed. I also made the argument of the `validate` callback somewhat(?) typed.
This way, the Yup integration continues to work exactly as before, but now, even ~~cavemen~~ people that need something different who decide to use a raw `validate` function can still get a typed schema. This also helps possibly integrating other validation libraries with Clipanion.
BTW, all that generic weirdness is necessary. I've tried every other possible combination, but this is the single one that doesn't cause **everything** to break.
```ts
// TS complains
static schema = 'foo';
// TS still complains
static …
```

feat: typed schema

---

README.md
sources/advanced/Command.ts
sources/core.ts
tests/advanced.test.ts
tests/core.test.ts

There is no official support for having arguments that can only get a value via binding (`--x=y`) and fallback on being a boolean flag when no value is provided.
This is currently possible but was not intended, and prone to breakage.
A use case can be found here: https://github.com/yarnpkg/berry/pull/1358
As discussed in https://github.com/yarnpkg/berry/pull/1358 , I added the ability for a Command.String to explicitly support falling back as a boolean flag
I added an advanced end to end test to check that the CLI acts as expected without relying on manual configuration of the Command (which would hide an error in Command.String's constructor)
Note: There is a little overlap between this PR and #14 . At first, I only …

Command: Add support for String commands that can act as boolean flags too

---

.gitattributes

Since I've run `yarn pnpify --sdk`, the repo is showing up as 93.5% JavaScript, when it's actually 100% TypeScript.
I created a `.gitattributes` file to mark the `.vscode/pnpify` folder as `linguist-vendored`.

chore: create .gitattributes

---

package.json
sources/advanced/Cli.ts
sources/format.ts
yarn.lock

Chalk is a large library that we don't really use. I inlined the few terminal sequences that we actually need, and made it configurable by the user to decide whether they want color or not (with a sensible default based on whether stdout is a TTY, which is the commonly agreed pattern).

Removes chalk from the dependencies

---

package.json
rollup.config.js
sources/advanced/Cli.ts
sources/advanced/Command.ts
sources/advanced/index.ts
sources/constants.ts
sources/core.ts
sources/errors.ts
yarn.lock

Clipanion doesn't currently ship a ESM version
Got rid of the circular dependencies and bundle using rollup.

build: output esm version

---

sources/advanced/Cli.ts
sources/advanced/index.ts
tests/advanced.test.ts

This PR makes it possible to pass the Cli options as an argument to `Cli.from`. It also makes it so that all Cli options are exposed on the `MiniCli`.

feat: allow passing Cli options to Cli.from

---

sources/advanced/HelpCommand.ts
sources/core.ts
tests/advanced.test.ts

The builtin help command currently doesn't have a `path` property, even though the types say the property should exist.
This leads to errors in yarn:
```
$ yarn npm login --help
Type Error: Cannot read property 'join' of undefined
at exec (/path/to/yarn/packages/yarnpkg-cli/sources/main.ts:111:63)
at run (/path/to/yarn/packages/yarnpkg-cli/sources/main.ts:51:7)
```
Alternatively, the type of Cli.process could be modified to include the fact that it could return a command instance without path.

feat: add path to help command

---

sources/advanced/Cli.ts
sources/advanced/Command.ts
tests/advanced.test.ts

This PR adds the ability to provide a custom error handler via an `async catch()` method on the `Command`.
Example:
```ts
class MyCommand extends Command {
async execute() { 
throw new Error(`command failed`)
}
async catch(error: Error) {
// handle error
// you could then re-throw the error, call `super.catch(error)` or simply gracefully ignore the error
}
}
```

feat: allow to provide custom error handler

---

README.md

The example code of `Command.Array` was wrong so I fixed it.

fix(docs): fix typo on README.md

---

sources/advanced/Command.ts
tests/advanced.test.ts

Usecase: I'm generating commands based on a JSON schema, and I want to prevent name conflicts between the defined arguments and actual properties on the command implementation. For options there's no problem because the name the property has on the prototype isn't used at all in the usage text, but for positionals this yields
```
$ pt g @scope/package:schematic [--project-name #0] [--skip-install] [--parent-ts-config #0] [prop_--name]
```
I've prefixed positonals with `prop_--` to prevent any name clash.
The options are prefixed with `prop_` so `--project-name` maps to `prop_projectName`, but that isn't visible here.
With this change the usage statement could become
```
$ pt g @scope/package:schematic [--project-name #0] [--skip-install] [--parent-ts-config #0] [name]
```
which is a lot …

feat: allow a pretty name to be passed for positional arguments

---

README.md

Inheritance wasn't documented inside the README.
I've added a section about inheritance with a `BaseCommand` and a `--cwd` option as an example.

docs: document command inheritance

---

README.md
sources/advanced/Command.ts
tests/advanced.test.ts

Yet another fun experiment - `Command.Counter` - a boolean option counter.
Each time a boolean option is detected, the counter will be incremented. Each time the boolean option is negated, the counter will be reset to `0`. The counter isn't initially set to `0`, the user has to set a default instead.
This enables use cases such as `yarn install -vvv` (just an example, I'm not planning to implement it in Yarn).
Just like the documentation says, all combinations are allowed:
```bash
run
run -v
run -vv
run --verbose -v --verbose -v
run --verbose -v --verbose -v --no-verbose
```
I've also updated the documentation and added tests.

feat: Command.Counter - boolean option counter ("run -vvv")

---

README.md

The `required` option inside `Command.String` is true by default, but the readme example made it look like it was the other way around.

docs(readme): switch required option in Command.String example

---

sources/advanced/Cli.ts
sources/advanced/HelpCommand.ts
sources/core.ts
tests/core.test.ts

We currently display a fairly unhelpful message when calling CLIs without any parameter and when there is no default command:
```
Unknown Syntax Error: Command not found; did you mean one of:
0. yarn install [--frozen-lockfile]
1. yarn remove ...
2. yarn run [--json]
3. yarn run <scriptName> ...
4. yarn add [-D,--dev] [-P,--peer] [-E,--exact] [-T,--tilde] <pkgs> ...
While running
```
This diff changes that to instead print the general help.
```
Yarn Project Manager - v0.0.0
$ yarn <command>
Where <command> is one of:
yarn add [-D,--dev] [-P,--peer] [-E,--exact] [-T,--tilde] <pkgs> ...
add dependencies to the project
yarn remove ...
remove dependencies from the project
Script-related commands:
yarn run <scriptName> ...
undocumented
You can also print more details about any of these …
```

Displays the general help when no commands are provided

---

README.md
sources/advanced/Cli.ts
sources/advanced/Command.ts
sources/core.ts
tests/advanced.test.ts

Edit: The original description isn't accurate anymore, see https://github.com/arcanis/clipanion/pull/40#issuecomment-694146387 for an updated description.
~~Just a fun experiment I've played with during the past few hours: `Command.Tuple` - options accepting a fixed number of arguments.~~
~~This PR introduces a new `Command.Tuple(optNames: string, {length: number})` decorator, which allows for fixed arity options (other than `0` or `1`). This enables use cases such as `filter-players Player1 Player2 Player3 --by-position 1 2 3`.~~
~~It works by modifying `commandBuilder.registerOptions` to make it work correctly with arities higher than 1 (the same code is used even when the arity is `1`).~~
~~I've also added tests and updated the documentation.~~
~~My only concern about this that I …

feat: custom arity for Command.String and Command.Array

---

README.md
sources/advanced/Cli.ts
sources/advanced/Command.ts
sources/core.ts
tests/advanced.test.ts
tests/core.test.ts

Transformers were consuming positionals in broken ways, which caused things like a `Command.String({required: true})` after a `Command.Rest()` to not work correctly (`Command.String({required: true})` after `Command.String({required: false})` was also broken).
A lot of refactoring had to be done to handle every possible case, but now everything works correctly. (I'm not going to describe how I fixed things here, I've already described enough of my pain on Discord. The tests are all that's needed to understand what went horribly wrong before). I've also updated the documentation to include `Command.Rest` and `Command.Proxy`.

fix(advanced): fix positional consumption by transformers

---

sources/advanced/Cli.ts
sources/core.ts

I've experimented with using the option descriptions inside Yarn's CLI docs, but the option definitions have a few problems:
- The options with descriptions weren't excluded from the usage.
- The `options` field also included options without descriptions.
- The `options[].definition` field was simply a join rather than a full definition (which should also include the arity - `-p,--package #0`)
Also, the descriptions weren't formatted as markdown(ish) on the Command help page (useful to highlight backticks).
A small proof of concept of what the option descriptions could look like inside Yarn's CLI docs (after this PR is merged):

refactor: improve option definitions

---

package.json
sources/core.ts
yarn.lock

When I changed the signature of `commandBuilder.usage` in https://github.com/arcanis/clipanion/pull/46, I forgot to update the `setCandidateUsage` transition. Because `registerStatic` and `registerDynamic` are currently typed as any (I initially thought it was because of objects in template literals, but that wasn't the cause), I didn't notice this until today:
I've fixed the issue and I've also made it so that the callbacks are strongly typed to prevent such problems in the future.

fix: fix setCandidateUsage

---

sources/core.ts
tests/advanced.test.ts

This PR disallows double negations for options with arity 1, such as writing `--no-no-redacted` for an option called `--no-redacted`. This is because double negations don't make any sense, `--no-redacted` already implies the fact that it's always redacted unless this option is set, no matter how the stars align.

fix: don't allow double negations for options with arity 1

---

package.json
rollup.config.js
tsconfig.json
yarn.lock

Due to the library getting built into a single file rollup and webpack were having issues treeshaking unused code
Preserve modules and set `sideEffects` to false

build: fix treeshaking

---

tsconfig.json

The use of object spread is currently transpiled to `Object.assign` but that's unnecessary as object spread has been supported since `node@8.6.0`
Set build target to ES2018 - only change in build output is object spread

build: target es2018

---

tests/advanced.test.ts
website/docs/tips.md

The note on positional inheritance was outdated, the consumption order problem only existed because of the decorator evaluation order. It now works as expected since we use regular properties.

docs: update docs on positional inheritance

---

sources/advanced/options/Proxy.ts
sources/advanced/options/Rest.ts
website/docs/api/option.md
website/docs/tips.md
website/docs/validation.md

There were places in the documentation that referenced the outdated `Command.<option>` options.

docs: replace Command.* with Option.* where necessary

---

sources/advanced/options/String.ts

As I may have mentioned before, I've got a CLI with options generated based on a JSON Schema. To ensure the names don't clash (e.g. if there's an option called `execute`) all option properties are prefixed with `option_`. Validation errors contain this option name, which is confusing.
Even without my weird naming, I would argue that showing the actually used option rather than the property name is more user friendly.
Before:
```
ai build all --unknown-target foo
Usage Error: Invalid option validation for option_unknownTarget: expected a valid enumeration value (got "foo")
```
After:
```
ai build all --unknown-target foo
Usage Error: Invalid option validation for --unknown-target: expected a valid enumeration value (got "foo")
```

feat: print used flag instead of property name in validation error

---

README.md

**What changes this PR introduce ?**
- Fix the links of the badges
- Fix indentation of `Why` section to follow [markdownlint](https://github.com/DavidAnson/markdownlint) rules
I see that there is no `CHANGELOG.md` inside the repository, we could have one so it's easier to see what's changing between releases.
Maybe we could have a generated changelog thanks to a commit message guidelines.
Also we could add automated deployment to the npm registry.

docs(readme): fix links + markdownlint

---

sources/advanced/options/String.ts
tests/advanced.test.ts
tests/inference.ts

It seems 37ccb64eacc636182ca4daa972bbc1ad56bc38a8 introduced a little bug where the following:
```
opt = Option.String(`--foo`, `bar`);
```
Caused `opt` to be inferred as `string | boolean`. I believe this is due to the `tolerateBoolean` options being incorrectly set as optional in their alternatives, when they should instead be required (since otherwise TS will interpret the lack of options as tolerating boolean, which isn't the intended default behaviour).
I also fixed the interaction of `tolerateBoolean` w/ validators, since the validators probably shouldn't run on those values.
cc @paul-soporan

Fixes the types for Command.String

---

README.md

As discussed on Discord, I added a `Migration` section in the README, which mentions the codemod I wrote - `clipanion-v3-codemod`, which can migrate nearly all Clipanion v2 code to v3 (except schemas and multiple option decorators on the same class property, but it warns on those cases). It even supports the fallback syntax.
The codemod is also heavily tested and it can successfully migrate the entire Yarn codebase (tested on the commit before you migrated manually) except schemas and the case with multiple option decorators.

docs: mention clipanion-v3-codemod in readme

---

sources/advanced/options/String.ts
tests/inference.ts

Hi,
The type definitions are giving the wrong type for positional arguments specified with `{ required: true }`:
Not sure if there's a preferred way to do the definitions but this PR is my attempt + updated inference tests.

fix: Fix type inference for explicitly required positionals.

---

sources/advanced/options/String.ts
tests/advanced.test.ts

Hi,
I noticed validators weren't being applied to positional arguments; this PR is to fix that issue and add a corresponding test case.

fix: Coerce positionals if validator is supplied

---

sources/advanced/Cli.ts

This changes the privacy modifiers for several methods and fields in the `Cli` class to make it easier/cleaner to re-use and override them in subclasses.
The use case that I'm trying to solve is to be able to customize how the help text is formatted and what information is displayed in it. At the moment this involves fighting/suppressing TypeScript warnings in several places.

Make it easier for `Cli` subclasses to override methods

---

sources/advanced/Cli.ts
tests/advanced.test.ts

It may sound a little weird to have to use `this.context.stdout.write` to write to the console in a Node context (developers are used to just call `console.log` for that). While it's important to keep this distinction in order to let commands be chainable (ie one command may call others and capture their output), newest Node releases may provide us an interesting tool to improve the user experience.
This diff introduces a new option, `enableCapture`. When set (the default is `false` at the moment), passing non-standard streams to a CLI execution will cause Clipanion to register itself into the `process.stdout.write` pipeline (same for stderr), effectively capturing everything that JS code would print. Asynchronicity shouldn't be an issue thanks to …

Implements stream capture

---

sources/advanced/Command.ts

We were seeing an issue in yarn v3.0.2 when using the workspaces plugin
where it was possible for a command's `schema` prop to be not
`undefined`, but also not an array. The issue is captured in the yarn
repository here: https://github.com/yarnpkg/berry/issues/3108
In order to ensure that `applyCascade()` is only called with valid
arguments, rather than checking that `cascade` is not `undefined`,
ensure that it is an `Array`. Otherwise, when we try to iterate over it,
we get a Type Error stating that `followups.every()` is not a function.

Make Type Check In `validateAndExecute()` Stricter

---

sources/advanced/Cli.ts
sources/advanced/index.ts
sources/format.ts

- `cli.format` wasn't exported on the `MiniCli`
- `formatMarkdownish` wasn't exported from the entry point
- I need to use them in Yarn

feat: export cli.format and formatMarkdownish

---

sources/format.ts

Hi,
Just a quick one; I noticed detailed descriptions with multiple lines are missing spaces between some words after they get unwrapped by `formatMarkdownish`:
```ts
class TestCommand extends Command {
static usage = Command.Usage({
description: 'Test command.',
details: `
This is the detailed description. As
part of the process of formatting it
for display, single newlines will be
replaced with spaces.
Multiple newlines are interpreted as
a paragraph break, and replaced with
a single newline.`
})
async execute () {}
}
```
Currently produces this:
``` 
$ yarn ts-node test.ts --help
Test command.
━━━ Usage ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
$ ...
━━━ Details ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
This is the detailed …
```

fix: Fixed markdownish text missing spaces.

---

.yarn/sdks/typescript/lib/tsserverlibrary.js
package.json
sources/advanced/Cli.ts
sources/advanced/index.ts
tests/inference.ts
website/docs/api/cli.md
website/docs/api/helpers.md
website/docs/getting-started.md

Clipanion is currently a little annoying to use with single-command scripts because of its boilerplate. The new `runExit` API lets you write small CLIs even more easily:
```ts
import {Command, runExit} from 'clipanion';
runExit(class extends Command {
async execute() {
// ...
}
});
```

Implements `runExit`

---

sources/advanced/Cli.ts
sources/advanced/options/String.ts
sources/advanced/options/utils.ts
tests/advanced.test.ts
website/docs/api/option.md
website/docs/contexts.md

I'm writing GitHub Actions powered by Clipanion, and some values (in particular `GITHUB_TOKEN`) are meant to be obtained from the environment. At the same time, it'd be beneficial to validate/coerce them like regular options and to allow options to override them. To this end, I added `env` into the context (which will be useful for [griselbrand](https://github.com/arcanis/griselbrand)) and added an option to inject environment variables after default values, but before options.

Adds .env option to Option.String

---

package.json
sources/advanced/options/Array.ts
sources/advanced/options/utils.ts
tests/specs/advanced.test.ts
tests/specs/inference.ts
yarn.lock

The `validator` option wasn't supported for `Option.Array`. This diff fixes that.

Implements array validation

---

sources/core.ts
tests/specs/advanced.test.ts

`--help` not working if an option is `required: true`.
fixes #101 
- `selectBestState` that runs the required field checks skips it if it's the help command
- Display the `--help` even if `--help --foo` has other options following
I think Unix commands usually display the help by default when you input an unknown option. That seems like a good practice to adopt

fix --help not working if required fields present

---

package.json
rollup.config.js
sources/advanced/Cli.ts
sources/platform/package.json
yarn.lock

https://github.com/arcanis/clipanion/pull/120 caused `./lib/advanced/Cli.mjs` to contain an unqualified import to the `platform` folder instead of the files in it.
Fixes https://github.com/nodejs/corepack/pull/349#discussion_r1443780153
Import the `node` platform directly, remove the `sources/platform/package.json` file, and add a `browser` and `module` field to the `publishConfig`.
This let's bundlers pick the `module` version and if they're bundling for a browser replace `./lib/platform/node*` with `./lib/platform/browser*`.

fix: use the browser field in the root `package.json`

---

website/docs/help.md

The documentation isn't aligned with the builtin `help`.
The [Builtin doc](https://mael.dev/clipanion/docs/api/builtins/#builtinshelpcommand) talks about a `--help` flag.
But the [Help command doc](https://mael.dev/clipanion/docs/help#the-help-command) talks about a full fledged `help` command.
Spoiler alert, the `help` command doesn't work and prints an error.
The `--help` flag is what works.
This PR fixes this and update the [Help command doc](https://mael.dev/clipanion/docs/help#the-help-command).
> [!WARNING]
> I'm not sure how the `#the-help-command` will be updated, or if it's in use somewhere else.
> [!NOTE]
> The <kbd>Edit this page</kbd> link isn't working as expected.

Update help.md with correct --help usage

---

sources/advanced/Cli.ts

Fixes #105
This is maybe a breaking change but you could also argue it's a bugfix that prevents undefined behavior.

feat: error if a command is registered twice
